### ISSUE TITLE
No module named YoutubeDL

### ISSUE THREAD

**Issue by paradoxical95** [logicguy1/PH-DL#1]
I ran the main.py file after installing python, and clicked Yes to make folders and install other modules, but then it threw an error saying youtube_dl not found.
I went to the repo that you linked for youtube_dl and copy pasted their youtube_dl.py into the modules folder, still the same error.
![image](https://github.com/logicguy1/PH-DL/assets/50901457/fdbf4ca2-766f-4e8b-bc49-00d2372e90c5)

How to fix this?

PS: will it work with links from p hub.org instead of .com, as .com redirects to .org now.

**Comment by MiraculousKnight** [comment]
You could get the youtube_dl module with,

>  pip install --upgrade youtube-dl
